# Enable C++ support
language: cpp


addons: 
  apt: 
    packages: libboost-all-dev

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc

    - os: linux
      dist: trusty
      sudo: required
      compiler: clang

    - os: osx
      osx_image: xcode8.2
      compiler: clang

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make
